### ISSUE TITLE
GCE stalling out before gh_ready=1 label added

### ISSUE THREAD

**Issue by delantai** [related-sciences/gce-github-runner#21]
Hi there, I'm giving this action a shot and running into an issue where the job times out with: 

`gce-gh-runner-2240820964-31953 not ready yet, waiting 5 secs ...`

I can see that the `./bin/installdependencies.sh && \\` step finishes well before the instance is deleted **and** I have the `gh_ready=0` label:

![image](https://user-images.githubusercontent.com/8430216/165814578-e67a83c5-6faf-49ea-9e12-4a817d8ed19d.png)

![image](https://user-images.githubusercontent.com/8430216/165816085-d3d98e88-6449-4a02-a176-7af67c190a6f.png)

And I also noticed that the `gh_ready=1` label is never added, so I suspect this is hanging up somewhere in:

```
RUNNER_ALLOW_RUNASROOT=1 ./config.sh --url https://github.com/${GITHUB_REPOSITORY} --token ${RUNNER_TOKEN} --labels ${VM_ID} --unattended ${ephemeral_flag} --disableupdate && \\
    ./svc.sh install && \\
    ./svc.sh start && \\
```

As you can see above, there are no more logs outputted from this step.  Typically I'd see some logs from `config.sh`, here's a screen of where I ran it in a manually created instance yesterday:

![image](https://user-images.githubusercontent.com/8430216/165815195-b51159e7-e74b-49fd-a069-2cea55748256.png)

I realize this probably isn't very helpful for debugging, but just wondering if anyone else may be experiencing this.

I'm using the following step configuration:

```
      - id: create-runner
        uses: related-sciences/gce-github-runner@v0.4
        with:
          token: ${{ secrets.token }}
          machine_zone: us-central1-a
          project_id: ${{ inputs.project_id }}
          service_account_key: ${{ secrets.service_account_key }}
```
