### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by moos3** [related-sciences/gce-github-runner#46]
So if you configure your workflow like so 
```
 steps:
      - id: create-runner
        uses: related-sciences/gce-github-runner@v0.10
        with:
          token: ${{ secrets.GH_SA_TOKEN }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          image_project: ubuntu-os-cloud
          image_family: ubuntu-2204-lts-arm64
          machine_zone: us-central1-a
          machine_type: t2a-standard-16
          boot_disk_type: pd-ssd
          runner_service_account: ${{ secrets.GCP_SA_EMAIL }}
          preemptible: false
          disk_size: 10
          arm: True
```

You will get this error ` - Invalid resource usage: 'Requested boot disk architecture (X86_64) is not compatible with machine type architecture (ARM64).'.` But if you copy down the the actions.sh and vendor/ folders locally using the latest version of the gcloud commands by running this
```
GITHUB_REPOSITORY_OWNER=moos3 GITHUB_RUN_ATTEMPT=1 GITHUB_RUN_ID=12309 GITHUB_REPOSITORY=boost-insurance/alpine-python ./action.sh --command=start --token=ghp_1238901yud9his0d \
--project_id=devops-moose-1234 --runner_ver=latest --machine_zone=us-central1-a \
--machine_type=t2a-standard-16 --network= --subnet= --accelerator= --disk_size=100 \
--scopes=cloud-platform --shutdown_timeout=30 --runner_service_account=gce-runner-sa@devops-moose-1234.iam.gserviceaccount.com   \
--image_project=ubuntu-os-cloud --image_family=ubuntu-2204-lts-arm64 \
--boot_disk_type=pd-ssd --preemptible=false --ephemeral=false \
--no_external_address=false --actions_preinstalled=false \
--maintenance_policy_terminate= --arm=true \
--service_account_key=1203912903812098
```

It will spin up a instance with no errors. But the the action fails for some odd reason. As the boot image and the instance type are both arm64. Can you assist with this?
